# Generated by Django 4.0.1 on 2022-03-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
